# Permalinks
#
permalink:           pretty
plugins: [jekyll-paginate]

# Setup
title:               GANs
tagline:             'quand la machine imagine'
description:         'Une introduction aux Generative Adversarial Networks'
url:                 https://francoispgm.github.io/
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              François Paugam
  url:               https://twitter.com/francois_vtecl
  email:             francois.paugam@ecl14.ec-lyon.fr

# Custom vars
version:             1.0.0
